name: ClangFormat Check
on: [push, pull_request]

jobs:
    format-check:
        name: Check Code Formatting
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path:
                    - src
                    - include
                    - lib
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Run clang-format style check
                uses: jidicula/clang-format-action@v4.15.0
                with:
                    clang-format-version: '20'
                    check-path: ${{ matrix.path }}
